name: Health Check Pipeline

on:
  push:
    branches:
      - main
    #schedule:
    #- cron: '30 10 * * *'

jobs:
  test_url:
    name: Test URL
    runs-on: ubuntu-20.04
    steps:
      - name: Test URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://purple-frog-1189.fly.dev/
          max-attempts: 3
          retry-delay: 10s
